package com.example.drink;

import androidx.appcompat.app.AppCompatActivity;

import android.app.Activity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        final String[] qArray = {"have an affair",
                "get married",
                "get knocked up",
                "throw trash out the window",
                "kill someone",
                "give money to the homeless",
                "get married to a sex doll",
                "burst into a song",
                "crash a car",
                "commit a train robbery",
                "break up a marriage",
                "play video games all day",
                "sleep all day",
                "die of stage fright",
                "become famous",
                "pay for a hooker",
                "kidnap a child",
                "get white girl wasted",
                "become someone we used to know",
                "get an std",
                "become a vigilante",
                "get bylaw called on them",
                "get a parking ticket",
                "fall down the stairs and die",
                "live in another country",
                "sleep with someone twice your age",
                "join a cult",
                "create a cult",
                "be on the news",
                "be a redneck",
                "vote for trump",
                "become a saint",
                "survive a zombie attack",
                "be the first voted off the island",
                "have a deep dark secret",
                "kill for money",
                "Have their spouse disappear",
                "own a tiger",
                "turn someone gay with meth",
                "be a undercover spy",
                "form a rebellion",
                "hack into the mainframe",
                "be kicked out of the looney bin",
                "get a sex concussion",
                "trip over their own feet",
                "call bylaw on their neighbour",
                "steal bread for a starving family",
                "commit tax fraud",
                "become prime minister",
                "sell their spouse on ebay",
                "be the first to be bitten by a zombie",
                "get down with the sickness",
                "have baby fever",
                "sell their kidney for the next iphone",
                "become homeless",
                "choke on a dick",
                "ruin a party",
                "become the grinch",
                "give a $5 gift card as a birthday present",
                "laugh to death",
                "work for cupcakes",
                "work as a hooker",
                "spill juice on the carpet",
                "lose a limb",
                "become rich",
                "die young",
                "live forever",
                "live at the gym",
                "sell their soul to save a life",
                "give a fake phone number",
                "be alone forever",
                "be into BDSM",
                "become an alcoholic",
                "cause a pandemic",
                "make the bed",
                "become a hoarder",
                "have a terabyte worth of porn",
                "get beaten up by a child",
                "steal candy from a baby",
                "forget thier child somewhere",
                "dress to impress",
                "give up on their dreams",
                "own 10 cats",
                "own 10 dogs",
                "pay $100 for a pen",
                "be caught outside",
                "nail a guitar solo",
                "go to jail",
                "rage quit",
                "flip the table",
                "smoke weed",
                "get their tongue stuck to a pole",
                "sniff their own fart",
                "fart in an elevator",
                "grow a tube baby",
                "become a monica",
                "become a ross",
                "become a joey",
                "become a chandler",
                "become a phoebe",
                "gamble their house away",
                "sell garbage for millions",
                "pose for a nude photo",
                "live with their parents forever",
                "cure cancer",
                "live in the jungle",
                "win big brother",
                "be a person everyone hates on reality tv",
                "write a popular book",
                "write a popular song",
                "become bald",
                "get randomly selected by airport security",
                "join a pyramid scheme",
                "gossip",
                "urinate in public",
                "join a gang",
                "own a sword",
                "free a whale from an aquarium",
                "go on a road trip",
                "kill their spouse with a frozen lamb then feed it to the cops",
                "send a nude",
                "get a surprise dick pic",
                "smuggle drugs in their butt",
                "become power hungry",
                "become a comedian",
                "create a popular game",
                "bring someone back from the dead",
                "sing a song confidently with the wrong lyrics",
                "tip over a cow",
                "live on a boat",
                "find a monster under their bed",
                "be friends with the monster under their bed",
                "pay at dinner",
                "lose their keys",
                "screw up there, their and they're",
                "make a robot",
                "order groceries online",
                "make a lit mix-tape",
                "pick their nose",
                "live their best life",
                "be a hufflepuff",
                "be a ravenclaw",
                "be a slitherine",
                "be a gryfindour",
                "get accepted at hogwarts",
                "teach sex-ed",
                "be the first to resort to cannibalism",
                "go a day without eating",
                "get fired from their job",
                "sass a mugger",
                "live of the grid",
                "go weeks without a shower",
                "be a disney princess",
                "own a shark",
                "bang ms.frizzle in the magic school bus",
                "have sex at church",
                "fall in love with themselves",
                "have sex on the first date",
                "own 100,000 books",
                "watch tv all day",
                "donate to a charity",
                "suggest a drinking game out of the blue",
                "butcher a language",
                "buy a fancy car",
                "catch feelings",
                "wave back and find out they were waving at someone else",
                "be a bad bitch",
                "experiment with the same gender",
                "be mistaken for the wrong gender",
                "sound like marge simpson",
                "give a 2 hour long lecture",
                "travel to space",
                "pee themselves",
                "grind at the club",
                "run a red light",
                "get pulled over for speeding",
                "start a pandemic",
                "spend all thier money on random stuff",
                "live the van life",
                "die trying to protect nature",
                "stalk a celebrity",
                "be on jerry springer",
                "get Tiktok famous",
                "cry after sex",
                "be apart of a scandal",
                "get botox",
                "get fired from thier job",
                "trip over thier own foot",
                "kick a kid",
                "get accidently deported",
                "get offended",
                "break up so they can really feel the song",
                "own a poster saying live, laugh, love"};

        final Button button = findViewById(R.id.button2);
        button.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
                TextView mTextView = (TextView) findViewById(R.id.textView);
                // Code here executes on main thread after user presses button
                int random = (int)(Math.random() * (174 - 1 + 1) + 1);
                System.out.println(random);
                mTextView.setText(qArray[random]);

            }
        });
    }
}
